[build]
  functions = "functions"
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["~/static/storedata.json"]
[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "*"